server:
  port: ${PORT:8181}
logging:
  level:
    org:
      springframework: INFO
      hibernate: ERROR
---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/idgenerator-concateno
    username: devuser
    password: secret
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
flyway:
  placeholders:
    dbuser: ${spring.datasource.username}
---
spring:
  profiles: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
flyway:
  placeholders:
    dbuser: ${spring.datasource.username}